---
- name: s3 demo
  hosts: all
  connection: local
  gather_facts: yes
  tasks:
  - name: Save file in object storage
    amazon.aws.aws_s3_object:
      bucket: awx-demo-tf-state-001
      object: "/{{ org_id }}/{{ project_id }}/object.{{ ansible_date_time.epoch }}.yaml"
      content: "{{ lookup('template', 'templates/object.yaml.j2') }}"
      mode: put
      encrypt: false
      rgw: true
      s3_url: "http://ams3.digitaloceanspaces.com"
