---
- name: s3 demo
  hosts: all
  connection: local
  gather_facts: yes
  tasks:
  - name: Save file in object storage
    amazon.aws.aws_s3:
      bucket: sra-incoming-payload
      object: "/{{ org_id }}/{{ project_id }}/object.{{ ansible_date_time.epoch }}.yaml"
      content: "{{ lookup('template', 'templates/object.yaml.j2') }}"
      mode: put
      encrypt: false
      s3_url: "http://s3.eu-de.cloud-object-storage.appdomain.cloud"
